### ISSUE TITLE
LDDTool 14.0 is not executing correctly as a GitHub action

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/gh-action-pds4-ldd#2]
## 🐛 Describe the bug
After making a minor change to ldd-survey, the GitHub actions are now failing:
(https://github.com/pds-data-dictionaries/ldd-survey/actions/runs/2163184314)

A sample of the type of error that is showing up (
[lddtool_run_log_20220413185744.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484031/lddtool_run_log_20220413185744.txt)
):
```
>>  ERROR missing superClass in master while trying to set subClassOf - lClass.identifier:0001_NASA_PDS_1.pds.Input_Data -  lClass.subClassOfTitle:TBD_subClassOfTitle
>>  ERROR missing superClass in master while trying to set subClassOf - lClass.identifier:0001_NASA_PDS_1.pds.Methods -  lClass.subClassOfTitle:TBD_subClassOfTitle
>>  ERROR missing superClass in master while trying to set subClassOf - lClass.identifier:0001_NASA_PDS_1.pds.Output_Data -  lClass.subClassOfTitle:TBD_subClassOfTitle
>>  ERROR missing superClass in master while trying to set subClassOf - lClass.identifier:0001_NASA_PDS_1.pds.Schematron_Assert -  lClass.subClassOfTitle:TBD_subClassOfTitle
>>  ERROR missing superClass in master while trying to set subClassOf - lClass.identifier:0001_NASA_PDS_1.pds.Schematron_Rule -  lClass.subClassOfTitle:TBD_subClassOfTitle
>>  ERROR 11179 data dictionary attribute is missing for overwrite - Identifier:DataElement.DE.0001_NASA_PDS_1.pds.Activity.pds.activity_type
>>  ERROR 11179 data dictionary attribute is missing for overwrite - Identifier:DataElement.DE.0001_NASA_PDS_1.pds.Activity.pds.description
>>  ERROR 11179 data dictionary attribute is missing for overwrite - Identifier:DataElement.DE.0001_NASA_PDS_1.pds.Activity.pds.title
```

It appears that something the new release of LDDTool is causing this. Yesterday's builds with LDDTool 13.1 didn't have this sort of issue: 
[lddtool_run_log_20220412224808.txt](https://github.com/NASA-PDS/pds4-information-model/files/8484032/lddtool_run_log_20220412224808.txt)

Additionally, this does not happen with the released version of LDD tool when I run it in my local environment. It seems to work correctly.

## 📜 To Reproduce
1. Go to https://github.com/pds-data-dictionaries/ldd-survey/actions/runs/2163184314
2. Click on Re-run jobs
3. Scroll down to Line 317 of LDD Build (1.17.0.0)

## 🕵️ Expected behavior
The GitHub action should pass, or at least not fail at LDD generation.

## 📚 Version of Software Used
NASA-PDS/gh-action-pds4-ldd@main (according to ldd-ci.yml)

## 🩺 Test Data / Additional context
https://github.com/pds-data-dictionaries/ldd-survey/actions/runs/2163184314

## 🖥 System Info

---

**Comment by jstone-psi** [comment]
I was incorrect, this does happen with the command line version, after all. I will file an issue against nasa-pds/pds4-information-model.

**Comment by jstone-psi** [comment]
Issue created against lddtool: https://github.com/NASA-PDS/pds4-information-model/issues/463

**Comment by jordanpadams** [comment]
closed per fix here:  https://github.com/NASA-PDS/pds4-information-model/issues/463
